#!/bin/bash
echo "[+] Install ubuntu:$1 PwnDocker Image"

docker build --no-cache --tag ubuntu:$1 ./ubuntu$1/
if [ $? -ne 0 ]; then
    echo "[!] Unsupported version: $1"
    exit 1
fi

chmod 755 ./pwndocker && cp ./pwndocker /bin/
chmod 755 ./pwnpush && cp ./pwnpush /bin/
chmod 755 ./pwnpull && cp ./pwnpull /bin/

docker run -it --cap-add SYS_PTRACE --name $1 ubuntu:$1 /bin/bash
if [ $? -ne 0 ]; then
    echo "[!] Unsupported version: $1"
    exit 1
fi

echo "[+] Execute Shell ubuntu:$1"
