#!/bin/bash

echo "[*] Running ubuntu:$1 version pwndocker..."
echo "[*] Booting.. ubuntu:$1 version"

docker start $1 && docker attach $1
if [ $? -ne 0 ]; then
    echo "[!] Unsupported version: $1"
    exit 1
fi

echo "[+] Finish Shell ubuntu:$1"
