#!/bin/bash

export TZ=Asia/Seoul
export PYTHONIOENCODING=UTF-8
export LC_CTYPE=C.UTF-8

apt update
apt install -y netcat
apt install vim git gcc ssh curl wget gdb sudo zsh tmux python3 python3-pip libffi-dev build-essential libssl-dev libc6-dbg make cmake pkg-config -y

python3 -m pip install --upgrade pip
pip3 install unicorn keystone-engine pwntools ropgadget

apt install libcapstone-dev -y

wget https://github.com/hugsy/gef/archive/refs/tags/2020.03.tar.gz
tar -xzvf 2020.03.tar.gz
echo "source ~/gef-2020.03/gef.py" >> ~/.gdbinit

apt install ruby-full -y
gem install one_gadget seccomp-tools

ln -s /lib/ld-linux-armhf.so.3 /lib/ld-linux.so.3