#!/bin/bash

export TZ=Asia/Seoul
export PYTHONIOENCODING=UTF-8
export LC_CTYPE=C.UTF-8

apt update
apt install -y netcat
apt update
apt install -y vim git gcc ssh curl wget gdb sudo zsh tmux python3 python3-dev python3-pip libffi-dev build-essential libssl-dev libc6-dbg gcc-multilib make

pip3 install unicorn keystone-engine pip==20.3.4 pwntools capstone ropper ropgadget

wget https://github.com/hugsy/gef/archive/refs/tags/2020.03.tar.gz
tar -xzvf 2020.03.tar.gz
echo "source ~/gef-2020.03/gef.py" >> ~/.gdbinit

apt-get install software-properties-common -y
apt-add-repository ppa:brightbox/ruby-ng
apt-get update
apt-get install ruby2.4 -y
apt-get install ruby-switch -y
ruby-switch --set ruby2.4
apt-get install gem -y
gem install one_gadget
