#!/bin/bash

export DEBIAN_FRONTEND=noninteractive
export TZ=Asia/Seoul
export PYTHONIOENCODING=UTF-8
export LC_CTYPE=C.UTF-8

cd /root

apt update
apt upgrade -y
apt-get update

apt install python3 python3-dev python3-pip -y
apt install git curl wget vim zsh gdb make -y
apt install libffi-dev build-essential libssl-dev libc6-dev libc6-dbg gcc make tmux -y

pip3 install unicorn keystone-engine pip==20.3.4 pwntools capstone ropper ropgadget

wget https://github.com/hugsy/gef/archive/refs/tags/2020.03.tar.gz
tar -xzvf 2020.03.tar.gz
echo "source ~/gef-2020.03/gef.py" >> ~/.gdbinit

apt-get install software-properties-common -y
apt-add-repository ppa:brightbox/ruby-ng
apt-get update
apt-get install ruby2.4 -y
apt-get install ruby-switch -y
ruby-switch --set ruby2.4
apt-get install gem -y
gem install one_gadget
